<h2>Topic 1: Introduction to Pandas</h2>

---

In [11]:
%%capture
%pip install pandas
%pip install numpy

import pandas
import numpy

---
<h3>Problem 1: How do we add two lists together like this:</h3>

<img src="./images/list.jpg" width="400" height="300">

---

In [12]:
L1 = [5, 3, 2, 7]
L2 = [2, 3, 4, 1]
L3 = L1 + L2
print(L3)

[5, 3, 2, 7, 2, 3, 4, 1]


---
<h4>Normal Python Lists allow concatenation (literally adding two lists together). But if we want a way to efficiently add each element together without writing a for loop we use what you call a Numpy Array:</h4>

---

In [17]:
L1 = numpy.array(L1)
L2 = numpy.array(L2)
L3 = L1 + L2
print(L3)

# If we still want to concatenate we can simply do:

L3 = numpy.concatenate((L1, L2))
print(L3)

[7 6 6 8]
[5 3 2 7 2 3 4 1]


---
<h4>The power really comes when it comes to higher dimensional data (e.g matrices) and Numpy fully supports it</h4>

---

In [ ]:
M1 = [[1, 2], [3, 4]]
M1 = numpy.array(M1)

print(M1 + 5, "\n") # Adds 5 to ALL entries

print(M1 * 5, "\n") # Multiplies 5 to ALL entries

print(M1 + M1 ** 2, "\n") # Adds the second power of itself to itself (Note that this is NOT matrix multiplication)

print(M1 @ M1) # Matrix Multiplication (we won't get into this)

[[6 7]
 [8 9]] 

[[ 5 10]
 [15 20]] 

[[ 2  6]
 [12 20]] 

[[ 7 10]
 [15 22]]


---

<h4> Now let's get into Pandas data structures, which are built on numpy arrays! Pandas has mainly two data structures:</h4>

#### 1. Series
#### 2. DataFrame

---

<h4> Pandas Series: </h4>

<img src="./images/series.jpg" height=300, width=400>

---

In [34]:
# Pandas Series

S1 = pandas.Series([9, 9, 3], index=[1, 2, 3])
S1

1    9
2    9
3    3
dtype: int64

In [37]:
# Extracting index and values of the series

print(S1.index)
print(S1.values)

Index([1, 2, 3], dtype='int64')
[9 9 3]


In [39]:
S1 + S1 * 2 # Operations only affect values not index

1    27
2    27
3     9
dtype: int64

In [43]:
S2 = np.concatenate((S1, S1)) # You can also use numpy functions on series (they are compatible)
S2

array([9, 9, 3, 9, 9, 3])

<h2>Topic 2: Data Querying</h2>

---

<h2>Topic 3: Data Manipulation</h2>

---

<h2>Topic 4: Working with Multiple Tables</h2>

---